name: CodeQuest CI

on:
  push:
    branches: [main]
    paths:
      - "python/**"
      - "cpp/**"
  pull_request:
    branches: [main]
    paths:
      - "python/**"
      - "cpp/**"

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'python') ||
      contains(join(github.event.pull_request.changed_files), 'python')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python Tests
        run: |
          cd python/week1_number_guessing
          python -m unittest discover -s tests

  cpp-tests:
    name: Run C++ Tests
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'cpp') ||
      contains(join(github.event.pull_request.changed_files), 'cpp')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run C++ Tests
        run: |
          cd cpp/week1_number_guessing/tests
          g++ test_number_guess.cpp -o test
          ./test
